---
title: "Heatmaps of DNA methylation levels"
---

```{r load_modules, echo=FALSE, include=FALSE}
library(pheatmap)
library(RColorBrewer)
```

Define settings
```{r define_opts, echo=FALSE}
if (grepl("ricard",Sys.info()['nodename'])) {
  source("/Users/ricard/scnmt_gastrulation_TetChimera/acc/heatmap/load_settings.R")
} else if (grepl("ebi",Sys.info()['nodename'])) {
  source("/homes/ricard/scnmt_gastrulation_TetChimera/acc/heatmap/load_settings.R")
} else {
  stop("Computer not recognised")
}
```

Load precomputed
```{r}
acc_dt <- fread(paste0(io$outdir,"/heatmap_acc.tsv.gz")) %>%
  .[anno%in%opts$annos] %>%
    merge(sample_metadata,by="id_acc") %>%
  .[,anno:=factor(anno,levels=opts$annos)]
```

```{r}
to.plot <- acc_dt %>% 
  merge(sample_metadata,by="id_acc") %>%
  .[,anno:=factor(anno,levels=opts$annos)]
```

<!-- # Tile plot -->

<!-- (Q) How to cluster -->

<!-- ```{r} -->
<!-- ggplot(to.plot, aes(x=sex, y=anno, fill=rate)) + -->
<!--   geom_tile(color="black") + -->
<!--   scale_fill_distiller(palette = "YlOrRd", direction=1) + -->
<!--   facet_wrap(~lineage) + -->
<!--   labs(x="", y="") + -->
<!--   theme_classic() + -->
<!--   theme( -->
<!--     axis.text = element_text(color="black"), -->
<!--     axis.line = element_blank(), -->
<!--     axis.ticks = element_blank(), -->
<!--     legend.title = element_blank() -->
<!--   ) -->
<!-- ``` -->

# Heatmap

```{r}
to.plot <- acc_dt %>%
  # .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("lineage","sex","anno")] %>%
  .[,.(rate=mean(rate)),by=c("lineage","anno")] %>%
  dcast(lineage~anno, value.var="rate") %>%
  matrix.please
```

```{r}
pdf(paste0(io$outdir,"/heatmap_acc_noESC.pdf"), useDingbats = F, onefile = F, width=16, height=7)
pheatmap(to.plot, 
  color = colorRampPalette(rev(brewer.pal(n=7, name ="Blues")))(100),
  cluster_rows = FALSE,
)
dev.off()
```
