---
title: "Box plots of DNA methylation levels"
---

```{r load_modules, echo=FALSE, include=FALSE}
library(ggpubr)
```

Define settings
```{r define_opts, echo=FALSE}
if (grepl("ricard",Sys.info()['nodename'])) {
  source("/Users/ricard/scnmt_gastrulation_TetChimera/met/boxplots/load_settings.R")
  # source("/Users/ricard/scnmt_gastrulation_TetChimera/metacc/boxplots/utils.R")
} else {
  stop("Computer not recognised")
}
```

# Load data

Load methylation data
```{r load_data, echo=FALSE, include=FALSE}
met_dt <- lapply(opts$met.annos, function(n) {
  fread(
    file = sprintf("%s/%s.tsv.gz",io$met_data_parsed,n),
    showProgress = F, header = F,
    select = c("V1"="factor","V2"="character","V3"="factor","V4"="integer","V5"="integer","V6"="integer")
    ) %>% .[V1%in%sample_metadata$id_met] %>% droplevels
}) %>% rbindlist %>% setnames(c("id_met","id","anno","Nmet","Ntotal","rate"))
```

Load results from the psedobulked differential analysis
```{r}
# diff.met <- lapply(opts$met.annos, function(x)
#   # fread(sprintf("%s/ICM_vs_TE_mural_%s.txt.gz",io$diff.met,x)) %>% .[,anno:=as.factor(x)]
#   fread(sprintf("%s/Epiblast_vs_PrE_%s.txt.gz",io$diff.met,x)) %>% .[,anno:=as.factor(x)]
# ) %>% rbindlist %>%
#   .[abs(diff_rate)>opts$min.met.diff] %>%
#   .[,c("id","anno","diff_rate")]
```

Load results from the differential analysis
```{r}
diff.met <- lapply(opts$met.annos, function(x)
  fread(sprintf("%s/ICM_vs_TE_mural_%s.txt.gz",io$diff.met,x)) %>% .[,anno:=as.factor(x)]
) %>% rbindlist %>%
  .[abs(diff)>opts$min.met.diff & padj_fdr<=opts$fdr.threshold] %>%
  .[,c("id","anno","diff","padj_fdr")]
```

```{r}
diff.met[,direction:=factor(diff>0)]
levels(diff.met$direction) <- c("High ICM","High TE")
diff.met[,.N,by=c("direction","anno")]
```

# Parse data

Merge data with metadata
```{r merge}
met_dt <- met_dt %>% merge(sample_metadata[,c("id_met","lineage","stage")], by="id_met")
```

Subset data using the significant hits
```{r}
met_dt.diff <- met_dt %>% merge(diff.met, by=c("id","anno"))
met_dt.nodiff <- met_dt[!id%in%met_dt.diff$id] %>% .[,direction:="NA"]
```


```{r}
# diff.met <- diff.met[diff>0]
# diff.met <- diff.met[diff<0]
# met_dt_sub <- met_dt %>% split(.$anno) %>%
#   map2(.,names(.), function(x,y) x[id%in%diff.met[sig==T & anno==y,id]]) %>%
#   rbindlist %>% droplevels
```

<!-- Filter by minimum number of measurements per cell -->
```{r}
# opts$min.met.observations <- 10
# met_dt_sub <- met_dt_sub[,N:=.N, by=c("sample","stage_lineage","anno")] %>%
#   .[N>=opts$min.met.observations] %>% .[,N:=NULL]
```

<!-- Regress out differences in global methylation or accessibility rate -->
```{r}
# foo <- fread(io$met.stats) %>% .[,c("id_met","mean")]
# met_dt_sub <- met_dt_sub %>% merge(foo, by="id_met") %>%
#   .[,new_rate:=mean(rate) + lm(formula=rate~mean)[["residuals"]], by=c("id","anno")]
```

# Plot

```{r}
to.plot <- met_dt.diff %>%
  .[,.(
    rate = 100*(sum(Nmet)/sum(Ntotal)), 
    Nmet = sum(Nmet), 
    Ntotal = sum(Ntotal)
  ), by=c("id_met","lineage","anno","direction")]

# %>% .[,anno:=stringr::str_replace_all(anno,opts$met.annos)]
  # .[,stage_lineage:=factor(stage_lineage, levels=names(colors))]
```

Boxplots with methylation rate per genomic context and lineage
```{r}
for (i in unique(to.plot$anno)) {
  p <- ggplot(to.plot[anno==i], aes(x=lineage, y=rate)) +
    geom_boxplot(outlier.shape=NA, coef=1) +
    # geom_boxplot(aes(fill=stage_lineage), outlier.shape=NA, coef=1) +
    # scale_fill_manual(values=colors) +
    labs(x="", y="methylation (%)") +
    facet_wrap(~anno+direction, ncol=2, scales="fixed") +
    # coord_cartesian(ylim=c(0,40)) +
    theme_bw() +
    # guides(color=F, fill=F) +
    # theme_pb() +
    theme(
      # strip.background = element_rect(fill="#F37A71"),
      axis.text.x = element_text(size=rel(1.0), color="black", angle=40, vjust=1, hjust=1),
      # axis.text.y = element_text(size=rel(1.2), color="black"),
      # axis.title.y = element_text(size=rel(1.4), color="black"),
      # strip.background = element_rect(fill="#F37A71"),
      # strip.text = element_text(size=rel(1.8), color="black"),
      # legend.position="top",
      # legend.title = element_blank()
    )
  
  pdf(sprintf("%s/boxplots_met_%s.pdf",io$outdir,i), width=7, height=5)
  print(p)
  dev.off()
}
```

Variability per genomic feature
```{r}
# to.plot <- rbind(
#     met_dt.diff %>% .[,.(var=var(rate)), by=c("id","stage","anno","direction")] %>% .[,class:="Diff"],
#     met_dt.nodiff %>% .[,.(var=var(rate)), by=c("id","stage","anno","direction")] %>% .[,class:="No diff"]
# )
# 
# to.plot[,mean(var,na.rm=T),by=c("class","stage")] %>% View
# 
# p <- ggplot(to.plot, aes(x=stage, y=var, fill=class)) +
#   geom_boxplot(outlier.shape=NA) +
#   labs(x="", y="Methylation variance") +
#   facet_wrap(~anno+direction, ncol=2, scales="fixed") +
#   theme_bw() +
#   theme(
#     strip.background = element_rect(fill="#F37A71"),
#     axis.text.x = element_text(size=rel(1.0), color="black", angle=40, vjust=1, hjust=1),
#   )
# 
# # pdf(paste0(io$outdir,"/boxplots_met.pdf"), useDingbats = F, onefile = F, width=7, height=5)
# print(p)
# # dev.off()
```

