samples:
    - E7.5_rep1
    - E7.5_rep2
    - E8.0_rep1
    - E8.0_rep2
    - E8.5_rep1
    - E8.5_rep2
    - E8.75_rep1
    - E8.75_rep2

# stages:
#     - E7.5
#     - E8.0
#     - E8.5
#     - E8.75

#################
## Directories ##
#################

directories:
    base: /bi/group/reik/ricard/data/gastrulation_multiome_10x
    original_data: /bi/group/reik/ricard/data/gastrulation_multiome_10x/original
    processed_data: /bi/group/reik/ricard/data/gastrulation_multiome_10x/processed_new/rna
    results: /bi/group/reik/ricard/data/gastrulation_multiome_10x/results_new
    atlas: /bi/group/reik/ricard/data/pijuansala2019_gastrulation10x

###############
## Resources ##
###############

resources:
    marker_genes: /bi/group/reik/ricard/data/pijuansala2019_gastrulation10x/results/marker_genes/all_stages/marker_genes.txt.gz
    umap: "/bi/group/reik/ricard/data/gastrulation_multiome_10x/results_new/rna/dimensionality_reduction/umap_features1000_pcs30_neigh25_dist0.3.txt.gz"
    celltypes: ["Epiblast", "Primitive_Streak", "Caudal_epiblast", "PGC", "Anterior_Primitive_Streak", "Notochord", "Def._endoderm", "Gut", "Nascent_mesoderm", "Mixed_mesoderm", "Intermediate_mesoderm", "Caudal_Mesoderm", "Paraxial_mesoderm", "Somitic_mesoderm", "Pharyngeal_mesoderm", "Cardiomyocytes", "Allantois", "ExE_mesoderm", "Mesenchyme", "Haematoendothelial_progenitors", "Endothelium", "Blood_progenitors_1", "Blood_progenitors_2", "Erythroid1", "Erythroid2", "Erythroid3", "NMP", "Rostral_neurectoderm", "Caudal_neurectoderm", "Neural_crest", "Forebrain_Midbrain_Hindbrain", "Spinal_cord", "Surface_ectoderm", "Visceral_endoderm", "ExE_endoderm", "ExE_ectoderm", "Parietal_endoderm"]
    stages: ["E7.5","E8.0","E8.5","E8.75"]
    TFs_file: "/bi/group/reik/ricard/data/mm10_regulation/TFs/TFs.txt"
    cell_metadata: "/bi/group/reik/ricard/data/gastrulation_multiome_10x/results_new/atac/archR/celltype_assignment/sample_metadata_after_celltype_assignment.txt.gz"

#############
## Scripts ##
#############

scripts:
    create_seurat: ../processing/1_create_seurat_rna.R
    qc: ../processing/2_QC.R
    seurat_to_sce: ../processing/3_seurat_to_SCE.R
    doublet_detection: ../processing/4_doublet_detection.R
    parse_doublets: ../processing/5_parse_sample_metadata_after_doublets.R
    mapping_mnn: ../mapping/run/mnn/mapping_mnn.R
    mapping_seurat: ../mapping/run/seurat/mapping_seurat.R
    parse_mapping: ../mapping/run/parse_sample_metadata_after_mapping.R
    dimensionality_reduction_sce: ../dimensionality_reduction/dimensionality_reduction_sce.R
    dimensionality_reduction_seurat: ../dimensionality_reduction/dimensionality_reduction_seurat.R
    pseudobulk_rna: ../pseudobulk/pseudobulk_rna.R
    celltype_validation_single_cells: ../celltype_validation/celltype_validation_single_cells.R
    celltype_validation_pseudobulk: ../celltype_validation/celltype_validation_pseudobulk.R
    plot_mapping_results: ../mapping/analysis/plot_mapping_umap.R
    plot_celltype_proportions: ../celltype_proportions/plot_celltype_proportions.R
    infer_trajectories: ../trajectories/infer_trajectory.R
    coexpression_TF_vs_gene_single_cells: ../TF2gene_coexpression/coexpression_TF_vs_gene_single_cells.R
    coexpression_TF_vs_gene_pseudobulk: ../TF2gene_coexpression/coexpression_TF_vs_gene_pseudobulk.R



################
## Parameters ##
################

pseudobulk_rna:
    # group_by: ["sample", "celltype.mapped_mnn", "celltype.mapped_seurat"]
    group_by: ["celltype.mapped_mnn", "celltype.mapped_seurat"]
    normalisation_method: "cpm"
    
doublet_detection:
    doublet_score_threshold: 1.25

mapping_mnn:
    atlas_stages: ["E6.5","E6.75","E7.0","E7.25","E7.5","E7.75","E8.0","E8.25","E8.5"]
    npcs: 50
    n_neighbours: 25

mapping_seurat:
    atlas_stages: ["E6.5","E6.75","E7.0","E7.25","E7.5","E7.75","E8.0","E8.25","E8.5"]
    npcs: 50
    n_neighbours: 25

qc:
    min_nFeature_RNA: 2000
    max_nFeature_RNA: 10000
    percent_mt: 40
    percent_rib: 20

dimensionality_reduction_sce:
    npcs: 50
    features: 2500
    n_neighbors: 25
    min_dist: 0.5
    vars_to_regress: ["nFeature_RNA"]
    colour_by: ["sample", "stage", "celltype.mapped_mnn", "celltype.mapped_seurat", "doublet_score", "doublet_call", "nFeature_RNA"]

dimensionality_reduction_seurat:
    npcs: 50
    features: 2500
    n_neighbors: 25
    min_dist: 0.5
    seed: 42
    vars_to_regress: ["nFeature_RNA"]
    # vars_to_regress: ["nFeature_RNA","mitochondrial_percent_RNA"]
    colour_by: ["sample", "stage", "celltype.mapped_mnn", "celltype.mapped_seurat", "doublet_score", "doublet_call", "nFeature_RNA"]

celltype_validation_single_cells:
    celltype_label: "celltype.mapped_mnn"

celltype_validation_pseudobulk:
    celltype_label: "celltype.mapped_mnn"

plot_celltype_proportions:
    celltype_label: "celltype.mapped_mnn"
    # celltype_label: ["celltype.mapped_seurat","celltype.mapped_mnn"]

infer_trajectories:
    # trajectory_name: ["blood", "ectoderm", "endoderm", "mesoderm"]
    trajectory_name: ["blood"]
    celltype_label: "celltype.mapped_mnn"

# coexpression_TF_vs_gene_trajectories

###########
## Slurm ##
###########

slurm:  # memory in MB
    create_seurat: 
        memory: 50000
        threads: 1
    qc: 
        memory: 3000
        threads: 1
    seurat_to_sce:
        memory: 50000
        threads: 1
    doublet_detection:
        memory: 25000
        threads: 1
    parse_doublet_results:
        memory: 2000
        threads: 1
    pseudobulk_rna:
        memory: 15000
        threads: 1
    mapping_mnn:
        memory: 50000
        threads: 1
    mapping_mnn_all_samples:
        memory: 50000
        threads: 1
    mapping_seurat:
        memory: 150000
        threads: 1
    mapping_seurat_all_samples:
        memory: 150000
        threads: 1
    parse_mapping_results:
        memory: 2000
        threads: 1
    dimensionality_reduction_sce:
        memory: 20000
        threads: 1
    dimensionality_reduction_seurat:
        memory: 50000
        threads: 1
    celltype_validation_single_cells:
        memory: 15000
        threads: 1
    celltype_validation_pseudobulk:
        memory: 3000
        threads: 1
    plot_mapping_results:
        memory: 3000
        threads: 1
    plot_celltype_proportions:
        memory: 3000
        threads: 1
    infer_trajectories:
        memory: 10000
        threads: 1
    coexpression_TF_vs_gene_single_cells:
        memory: 35000
        threads: 1
    coexpression_TF_vs_gene_single_cells_denoised:
        memory: 150000
        threads: 1
    coexpression_TF_vs_gene_pseudobulk:
        memory: 5000
        threads: 1


        