---
title: "Human multi-omics: quality control of methylation data"
---

```{r load_modules, include=FALSE, echo=FALSE}
library(tidyr)
library(cowplot)
```


```{r funcs, echo=FALSE}
barplot_theme <- function() {
  p <- theme(
    axis.title.x = element_blank(),
    axis.title.y = element_text(colour="black", size=15),
    axis.text.y = element_text(colour="black",size=rel(1.2)),
    axis.line = element_line(colour="black", size=rel(0.7)),
    axis.ticks = element_line(colour="black", size=rel(0.7)),
    legend.position="none",
    panel.background = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_blank()
  )
}
```

```{r}
if (grepl("ricard",Sys.info()['nodename'])) {
  source("/Users/ricard/scnmt_gastrulation_TetChimera//settings.R")
} else {
  stop("Computer not recognised")
}
io$outdir <- paste0(io$basedir,"/met/results/qc")
```

Define options
```{r define_opts, echo=FALSE, include=FALSE}
opts$met_nCG_threshold <- 1e4
opts$max.meth.rate <- 50
opts$min.meth.rate <- 10
```

Update sample metadata
```{r load_metadata}
sample_metadata <- sample_metadata %>% .[!is.na(id_met)]
```

Load methylation statistics
```{r}
stats <- fread(io$met.stats)
```

# Plot

```{r}
to.plot <- stats %>% merge(sample_metadata,by="id_met")
```


Barplots with nCG per cell
```{r}
tmp <- to.plot[,c("id_met","nCG")] %>% setkey(nCG) %>% .[,id_met:=factor(id_met,levels=id_met)]

p <- ggplot(tmp, aes(x=id_met, y=log10(nCG))) +
  geom_bar(stat="identity", position="dodge", fill="#F8766D", color="#F8766D") +
  labs(title="", x="", y="Number of observed CpG sites (log10)") +
  geom_hline(yintercept=log10(opts$met_nCG_threshold), colour="black", linetype="dashed") +
  barplot_theme() +
  # scale_y_continuous(expand=c(0,0), limits=c(0,4e+6)) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
print(p)

# pdf(file=paste0(io$outdir,"/qc_met.pdf"), width=8, height=5)
# print(p1)
# dev.off()
```

Barplots with global levels per cell
```{r}
tmp <- to.plot[,c("id_met","rate")] %>% setkey(rate) %>% .[,id_met:=factor(id_met,levels=id_met)]

p <- ggplot(tmp, aes(x=id_met, y=rate)) +
  geom_bar(stat="identity", position="dodge", fill="#F8766D", color="#F8766D") +
  labs(title="", x="", y="Global methylation (%)") +
  geom_hline(yintercept=opts$max.meth.rate, colour="black", linetype="dashed") +
  geom_hline(yintercept=opts$min.meth.rate, colour="black", linetype="dashed") +
  barplot_theme() +
  # scale_y_continuous(expand=c(0,0), limits=c(0,4e+6)) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
print(p)

# pdf(file=paste0(io$outdir,"/qc_met.pdf"), width=8, height=5)
# print(p1)
# dev.off()
```

```{r}
print("Fail QC for methylation:")
failqc <- stats %>%
  # .[((rate<opts$min.meth.rate) | (rate>opts$max.meth.rate))] %>%
  .[(nCG<opts$met_nCG_threshold) | (rate<opts$min.meth.rate | rate>opts$max.meth.rate)] %>%
  .[,id_met]

print(length(failqc))
```

```{r}
to.plot <- stats %>%
  .[,pass_metQC:=ifelse(id_met%in%failqc,F,T)]

p <- ggplot(to.plot, aes(x=rate, y=log10(nCG), color=pass_metQC)) +
  geom_point() +
  geom_hline(yintercept=log10(opts$met_nCG_threshold), linetype="dashed", color="black") +
  geom_vline(xintercept=opts$min.meth.rate, linetype="dashed", color="black") +
  geom_vline(xintercept=opts$max.meth.rate, linetype="dashed", color="black") +
  labs(x="Global methylation (%)", y="Number of observed CpG sites") +
  scale_color_brewer(palette = "Dark2") +
  theme_classic()
print(p)

# pdf(file=paste0(io$outdir,"/qc_met.pdf"), width=8, height=5)
# print(p1)
# dev.off()
```


Update sample metadata
```{r}
sample_metadata_updated <- fread(io$metadata)
sample_metadata_updated <- sample_metadata_updated %>%
  .[id_met%in%stats$id_met, pass_metQC:=ifelse(id_met%in%failqc,FALSE,TRUE)]

table(sample_metadata_updated$pass_metQC)

# fwrite(sample_metadata_updated, io$metadata, sep="\t", na="NA")
```
