---
title: "Plot global statistics of DNA accessibility per cell"
---

```{r load_modules, echo=FALSE, include=FALSE}
library(ggpubr)
```

Load default settings
```{r define_opts, echo=FALSE}
source("/Users/ricard/scnmt_gastrulation_TetChimera/settings.R")
```

Define I/O 
```{r}
io$outdir <- paste0(io$basedir,"/acc/results/stats/pdf")
```

Define options
```{r}
```

Load pre-computed estimates
```{r read_stats, echo=FALSE}
stats <- fread(io$acc.stats)
```

# Plot

```{r}
to.plot <- stats %>% merge(sample_metadata, by="id_acc")
```

Boxplots with mean accessibility rate per lineage
```{r}
p <- ggboxplot(to.plot, x="plate", y="rate", fill="#00BFC4") +
  geom_jitter(alpha=0.5, color="#00BFC4", size=0.80) +
  # coord_cartesian(ylim=c(0,75)) +
  labs(x="", y="Global accessibility (%)") +
  theme(
    axis.text.y = element_text(size=rel(0.9))
  )
  # theme_bw() +
  # theme_pub()
print(p)


# pdf(paste0(io$outdir,"/globalacc_s.pdf"), width=9, height=5, useDingbats = F)
# print(p)
# dev.off()
```

Boxplots with coverage per lineage
```{r}
p <- ggboxplot(to.plot, x="plate", y="nGC", fill="#00BFC4") +
  geom_jitter(alpha=0.5, color="#00BFC4", size=0.80) +
  scale_y_log10() +
  labs(x="", y="Number of GCs") +
  theme(
    axis.text.y = element_text(size=rel(0.9))
  )
  # theme_bw() +
  # theme_pub()
print(p)
```

Correlation between mean accessibility rate and coverage
```{r}
# to.plot[,mean2:=log2(((mean/100)+0.01)/(1-(mean/100)+0.01))]

p <- ggscatter(to.plot, x="rate", y="nGC", color="plate") +
  yscale("log10", .format = TRUE) +
  geom_smooth(method="lm") +
  theme_classic()
  # theme_pub()

print(p)
```
