samples:
    - E7.5_TET_TKO
    - E7.5_TET_TKO_crispr
    - E7.5_TET_TKO_crispr
    - E8.5_WT_CD41+
    - E8.5_TET_TKO_CD41+
    - E8.5_WT_KDR+
    - E8.5_TET_TKO_KDR+
    - E8.5_WT_KDR+_CD41+
    - E8.5_TET_TKO_KDR+_CD41+
    - E8.5_WT
    - E8.5_TET_TKO

plates:
    - E7.5_tet_chimera_plate3
    - E7.5_tet_crispr_plate5
    - E7.5_tet_crispr_plate6
    - E8.5_oct20_plate1
    - E8.5_oct20_plate7
    - E8.5_oct20_plate5
    - E8.5_oct20_plate3
    - E8.5_oct20_plate4
    - E8.5_oct20_plate6
    - E8.5_oct20_plate2
    - E8.5_oct20_plate8


#################
## Directories ##
#################

directories:
    base: /bi/group/reik/ricard/data/tet_chimera_nmtseq
    processed_data: /bi/group/reik/ricard/data/tet_chimera_nmtseq/processed
    results: /bi/group/reik/ricard/data/tet_chimera_nmtseq/results

###############
## Resources ##
###############

resources:
    celltypes: ["Epiblast", "Primitive_Streak", "Caudal_epiblast", "PGC", "Anterior_Primitive_Streak", "Notochord", "Def._endoderm", "Gut", "Nascent_mesoderm", "Mixed_mesoderm", "Intermediate_mesoderm", "Caudal_Mesoderm", "Paraxial_mesoderm", "Somitic_mesoderm", "Pharyngeal_mesoderm", "Cardiomyocytes", "Allantois", "ExE_mesoderm", "Mesenchyme", "Haematoendothelial_progenitors", "Endothelium", "Blood_progenitors_1", "Blood_progenitors_2", "Erythroid1", "Erythroid2", "Erythroid3", "NMP", "Rostral_neurectoderm", "Caudal_neurectoderm", "Neural_crest", "Forebrain_Midbrain_Hindbrain", "Spinal_cord", "Surface_ectoderm", "Visceral_endoderm", "ExE_endoderm", "ExE_ectoderm", "Parietal_endoderm"]
    stages: ["E7.5","E8.5"]

#############
## Scripts ##
#############

scripts:
    calculate_global_stats_per_cell_met: ../stats/calculate_stats.R
    qc_met: ../processing/qc.R

################
## Parameters ##
################

# calculate_global_stats_per_cell_met:
#     group_by: ["celltype.mapped_mnn", "celltype.mapped_seurat"]
#     normalisation_method: "cpm"
    
###########
## Slurm ##
###########

slurm:  # memory in MB
    calculate_global_stats_per_cell_met: 
        memory: 5000
        threads: 1
    calculate_global_stats_per_cell_acc: 
        memory: 10000
        threads: 1
    plot_global_stats_per_cell_met: 
        memory: 3000
        threads: 1
    plot_global_stats_per_cell_acc: 
        memory: 3000
        threads: 1
    qc_met: 
        memory: 5000
        threads: 1
    qc_acc: 
        memory: 5000
        threads: 1
